app:
  name: "omni-crawler"
  version: "1.0.0"
  debug: true

crawler:
  max_concurrent_crawls: 5
  request_timeout: 30
  user_agent: "OmniCrawler/1.0 (+http://omnicroawler.com/bot)"
  respect_robots_txt: true
  crawl_interval_seconds: 300  # 5 minutes

discovery:
  rss_feeds:
    - "https://rss.cnn.com/rss/edition.rss"
    - "https://feeds.bbci.co.uk/news/rss.xml"
    - "https://feeds.npr.org/1001/rss.xml"
    - "https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best"

  # Add these 20+ major news sources:
    - "https://feeds.reuters.com/reuters/topNews"
    - "https://rss.cnn.com/rss/edition.rss"
    - "https://feeds.ap.org/APNews"
    - "https://feeds.nbcnews.com/nbcnews/public/news"
    - "https://abcnews.go.com/abcnews/topstories"
    - "https://feeds.foxnews.com/foxnews/latest"
    - "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
    - "https://www.washingtonpost.com/arcio/rss/"
    - "https://feeds.washingtonpost.com/rss/politics"
    - "https://feeds.washingtonpost.com/rss/business"
    - "https://feeds.washingtonpost.com/rss/world"
    - "https://feeds.skynews.com/feeds/rss/home.xml"
    - "https://feeds.skynews.com/feeds/rss/world.xml"
    - "https://www.theguardian.com/international/rss"
    - "https://feeds.feedburner.com/techcrunch/"
    - "https://feeds.arstechnica.com/arstechnica/index"
    - "https://www.wired.com/feed/rss"
    - "https://feeds.mashable.com/Mashable"
    - "https://rss.news.google.com/rss?hl=en-US&gl=US&ceid=US:en"
    - "https://feeds.bloomberg.com/bloomberg/politics"
    - "https://feeds.bloomberg.com/bloomberg/business"
    - "https://www.latimes.com/local/rss2.0.xml"
    - "https://www.chicagotribune.com/arcio/rss/"
    - "https://www.dallasnews.com/arcio/rss/"
  
  monitored_domains:
    - "bbc.com"
    - "cnn.com" 
    - "npr.org"
    - "reuters.com"

storage:
  elasticsearch:
    index: "news-articles"
    batch_size: 100
  
  postgres:
    table_articles: "articles"
    table_entities: "article_entities"

processing:
  min_article_length: 200
  enable_sentiment_analysis: true
  enable_entity_extraction: true
  enable_keyword_extraction: true