web:
  host: "0.0.0.0"
  port: 5000
  debug: false
  secret_key: "omni-crawler-secret-key-2024"

api:
  rate_limit: "100 per minute"
  enable_cors: true
  max_page_size: 100

security:
  enable_rate_limiting: true
  enable_csrf: true
  allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:5000"

monitoring:
  enable_metrics: true
  metrics_port: 5001